<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Subscribe_API</RootNamespace>
    <UserSecretsId>2feb8210-fc41-4a82-a750-50e7a8e5156e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Hangfire" Version="1.8.22" />
	  <PackageReference Include="Hangfire.AspNetCore" Version="1.8.22" />
	  <PackageReference Include="Hangfire.Core" Version="1.8.22" />
	  <PackageReference Include="Hangfire.PostgreSql" Version="1.20.13" />
	  <PackageReference Include="MassTransit" Version="8.5.7" />
	  <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
	  <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedModels\SharedModels.csproj" />
    <ProjectReference Include="..\SubscribeDb\SubscribeDb.csproj" />
  </ItemGroup>

</Project>
