services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672"
      - "15672"
    networks:
      - cania-network

  api-gateway:
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT_SECRET=YourSuperSecretKeyThatIsAtLeast32CharactersLong123!
      - JWT_ISSUER=Auth
      - JWT_AUDIENCE=Services
      - JwtSettings_ExpirationAccessTokenMinutes=15
      - JwtSettings_ExpirationRefreshTokenDays=7
    depends_on: [auth-api, user-api, task-api]
    networks:
      - cania-network

  auth-api:
    build: { context: ., dockerfile: AuthService/Dockerfile }
    ports:
      - "8081"
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - AUTH_DB_CONNECTION=Host=auth-db;Port=5432;Database=AuthDb;Username=postgres;Password=password;
      - RabbitMQ_Host=rabbitmq
      - JWT_SECRET=YourSuperSecretKeyThatIsAtLeast32CharactersLong123!
      - JWT_ISSUER=Auth
      - JWT_AUDIENCE=Services
      - JwtSettings_ExpirationAccessTokenMinutes=15
      - JwtSettings_ExpirationRefreshTokenDays=7

      - Google_ClientId=${Google_ClientId}
      - Google_SecretKey=${Google_SecretKey}
      - GitHub_ClientId=${GitHub_ClientId}
      - GitHub_SecretKey=${GitHub_SecretKey}
      - AUTH_HOST=localhost:8081
    depends_on: [auth-db, rabbitmq]
    networks: [cania-network]

  auth-db:
    image: postgres:15
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: password, POSTGRES_DB: AuthDb }
    networks: [cania-network]

  user-api:
    build: { context: ., dockerfile: UserService/Dockerfile }
    ports:
      - "8082"
    environment:
      - ASPNETCORE_HTTP_PORTS=8082
      - User_Db_Connection=Host=user-db;Port=5432;Database=UserDb;Username=postgres;Password=password;
      - RabbitMQ_Host=rabbitmq
    depends_on: [user-db, rabbitmq]
    networks: [cania-network]

  user-db:
    image: postgres:15
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: password, POSTGRES_DB: UserDb }
    networks: [cania-network]

  task-api:
    build: { context: ., dockerfile: TaskService/Dockerfile }
    ports:
      - "8086"
    environment:
      - ASPNETCORE_HTTP_PORTS=8086
      - TASK_DB_CONNECTION=Host=task-db;Port=5432;Database=TaskDb;Username=postgres;Password=password;
      - RabbitMQ_Host=rabbitmq
    depends_on: [task-db, rabbitmq]
    networks: [cania-network]

  task-db:
    image: postgres:15
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: password, POSTGRES_DB: TaskDb }
    networks: [cania-network]

  password-api:
    build: { context: ., dockerfile: PasswordService/Dockerfile }
    environment:
      - ASPNETCORE_HTTP_PORTS=8084
      - PASSWORD_DB_CONNECTION=Host=password-db;Port=5432;Database=PasswordDb;Username=postgres;Password=password;
      - RabbitMQ_Host=rabbitmq
    depends_on: [password-db, rabbitmq]
    networks: [cania-network]

  password-db:
    image: postgres:15
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: password, POSTGRES_DB: PasswordDb }
    networks: [cania-network]

  subscribe-api:
    build: { context: ., dockerfile: SubscribeService/Dockerfile }
    environment:
      - ASPNETCORE_HTTP_PORTS=8085
      - SUBSCRIBE_DB_CONNECTION=Host=subscribe-db;Port=5432;Database=SubscribeDb;Username=postgres;Password=password;
      - RabbitMQ_Host=rabbitmq
    depends_on: [subscribe-db, rabbitmq]
    networks: [cania-network]

  subscribe-db:
    image: postgres:15
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: password, POSTGRES_DB: SubscribeDb }
    networks: [cania-network]

  notification-api:
    build: { context: ., dockerfile: NotificationService/Dockerfile }
    environment:
      - ASPNETCORE_HTTP_PORTS=8083
      - NOTIFICATION_DB_CONNECTION=Host=notification-db;Port=5432;Database=NotificationDb;Username=postgres;Password=password;
      - RabbitMQ_Host=rabbitmq
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - Email__Smtp__Username=caniapentest@gmail.com
      - Email__FromEmail=caniapentest@gmail.com
    depends_on: [notification-db, rabbitmq]
    networks: [cania-network]

  notification-db:
    image: postgres:15
    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: password, POSTGRES_DB: NotificationDb }
    networks: [cania-network]

networks:
  cania-network:
    driver: bridge