<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Password_API</RootNamespace>
    <UserSecretsId>60c37a19-ad27-49b9-a889-1159d2fd920c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MassTransit" Version="8.5.7" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PasswordDb\PasswordDb.csproj" />
    <ProjectReference Include="..\SharedModels\SharedModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Responses\" />
  </ItemGroup>

</Project>
